version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/db/custom.db
    volumes:
      - ./db:/app/db
    restart: unless-stopped

  # Optional: Add a database service if you want to use PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: educlay
  #     POSTGRES_USER: educlay
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: